topk_expand=$1
python train.py --triple_name marco \
                --doc_id full \
                --model_name SpaDE_cotraining \
                --early_stop 5 \
                --verbose 800 \
                --test_step 1600 \
                --test_from 30400 \
                --sample_size 1024 \
                --train_batch_size 32 \
                --accumulation_size 8 \
                --test_batch_size 64 \
                --lr1 1e-5 \
                --lr2 5e-6 \
                --pairwise IBN \
                --pointwise1 False \
                --pointwise2 doc \
                --path1 saves/SpaDE_weight \
                --num_epoch1 0 \
                --path2 saves/SpaDE_expand \
                --num_epoch2 0 \
                --alpha 0.3 \
                --teaching_ratio 0.3 \
                --teaching_start_iter 32000 \
                --sparsifying_step 3200 \
                --sparsifying_method df_cutoff_btw \
                --sparsifying_ratio 0.7 \
                --expand_method2 topk \
                --sparsifying_start_iter 32000 \
                --sparsifying_gradual True \
                --num_expand2 $topk_expand \
                --topk_start_iter2 32000
